### ISSUE TITLE
build_docs.py fails on lines with more than 4 comment-characters

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1315]
The [documentation](https://github.com/Hammerspoon/hammerspoon/tree/master/scripts/docs) says:

> Any comment that starts with 4 comment-characters is ignored,

However, this will cause the `build_docs.py` script to fail:

```
--------------------------------------------------------------------------------
-- FUNCTION:
--------------------------------------------------------------------------------

```

Easy fix @cmsj ?

**Comment by cmsj** [comment]
Could you paste in the backtrace from the script please?

**Comment by latenitefilms** [comment]
Here you go:

```
Traceback (most recent call last):
  File "scripts/docs/bin/build_docs.py", line 598, in <module>
    main()
  File "scripts/docs/bin/build_docs.py", line 579, in main
    results = do_processing(arguments.DIRS)
  File "scripts/docs/bin/build_docs.py", line 349, in do_processing
    docs = process_docstrings(raw_docstrings)
  File "scripts/docs/bin/build_docs.py", line 226, in process_docstrings
    modulename = find_module_for_item(docs.keys(), itemname)
  File "scripts/docs/bin/build_docs.py", line 137, in find_module_for_item
    module = matches[-1]
IndexError: list index out of range
make: *** [build/docs.json] Error 1
```
