### ISSUE TITLE
codesigning issues

### ISSUE THREAD

**Issue by z3t0** [Hammerspoon/hammerspoon#1353]
Getting this when trying to build on Xcode. Not too sure what to do. I have created the Internal Code Signing cert...
```
/Users/z3t0/Library/Developer/Xcode/DerivedData/Hammerspoon-gwmnxzafgdaerrfpjbfyfnynzwha/Build/Products/Debug/Hammerspoon.app: code object is not signed at all
In subcomponent: /Users/z3t0/Library/Developer/Xcode/DerivedData/Hammerspoon-gwmnxzafgdaerrfpjbfyfnynzwha/Build/Products/Debug/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework
Command /usr/bin/codesign failed with exit code 1
```

```


echo "Building Hammerspoon in Debug configuration"
Building Hammerspoon in Debug configuration
rm -rf build/Hammerspoon.app
xcodebuild -workspace Hammerspoon.xcworkspace -scheme Hammerspoon -configuration Debug clean build > build/Debug-build.log
** BUILD FAILED **


The following build commands failed:
        CodeSign /Users/z3t0/Library/Developer/Xcode/DerivedData/Hammerspoon-gwmnxzafgdaerrfpjbfyfnynzwha/Build/Products/Debug/Hammerspoon.app
(1 failure)
make: *** [build/Hammerspoon.app] Error 65
scripts/docs/bin/build_docs.py -o build/ --sql Hammerspoon/ extensions/
mkdir -p build/html
rm -rf build/html/*
cp scripts/docs/templates/docs.css build/html
cp scripts/docs/templates/jquery.js build/html
cp build/docs.json build/html
cp build/docs_index.json build/html
scripts/docs/bin/build_docs.py -o build/ --html Hammerspoon/ extensions/
Traceback (most recent call last):
  File "scripts/docs/bin/build_docs.py", line 608, in <module>
    main()
  File "scripts/docs/bin/build_docs.py", line 600, in main
    arguments.title, results)
  File "scripts/docs/bin/build_docs.py", line 518, in write_html
    write_templated_output(output_dir, template_dir, title, data, "html")
  File "scripts/docs/bin/build_docs.py", line 486, in write_templated_output
    data = process_markdown(data)
  File "scripts/docs/bin/build_docs.py", line 300, in process_markdown
    import mistune
ImportError: No module named mistune
make: *** [build/html] Error 1

```
the second is from rebuild.sh

**Comment by z3t0** [comment]
figured it out...
